.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. trustnetworkglobalcoin_qt test_trustnetworkglobalcoin_qt
clean: FORCE
	$(MAKE) -C .. trustnetworkglobalcoin_qt_clean test_trustnetworkglobalcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_trustnetworkglobalcoin_qt_check
trustnetworkglobalcoin-qt trustnetworkglobalcoin-qt.exe: FORCE
	 $(MAKE) -C .. trustnetworkglobalcoin_qt
