.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tngc_qt test_tngc_qt
clean: FORCE
	$(MAKE) -C .. tngc_qt_clean test_tngc_qt_clean
check: FORCE
	$(MAKE) -C .. test_tngc_qt_check
tngc-qt tngc-qt.exe: FORCE
	 $(MAKE) -C .. tngc_qt
